[[main]]
  name = "About"
  url = "#about"
  weight = 1

[[main]]
  name = "Work in Progress"
  url = "/#work-in-progress"
  weight = 2

[[main]]
  name = "Publications"
  url = "/#publications"
  weight = 3

[[main]]
  name = "Experiences"
  url = "/#experiences"
  weight = 4

#[[main]]
#  name = "Posts"
#  url = "/posts/"
#  weight = 4
